// Code generated by protoc-gen-go. DO NOT EDIT.
// source: shared.proto

package shared

import (
	fmt "fmt"
	math "math"

	proto "github.com/golang/protobuf/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Headers struct {
	MessageId            uint32   `protobuf:"varint,2,opt,name=MessageId,json=messageId,proto3" json:"MessageId,omitempty"`
	ParentMessageId      uint32   `protobuf:"varint,3,opt,name=ParentMessageId,json=parentMessageId,proto3" json:"ParentMessageId,omitempty"`
	EpisodeId            uint32   `protobuf:"varint,4,opt,name=EpisodeId,json=episodeId,proto3" json:"EpisodeId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Headers) Reset()         { *m = Headers{} }
func (m *Headers) String() string { return proto.CompactTextString(m) }
func (*Headers) ProtoMessage()    {}
func (*Headers) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a4e87e678c5ced, []int{0}
}

func (m *Headers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Headers.Unmarshal(m, b)
}
func (m *Headers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Headers.Marshal(b, m, deterministic)
}
func (m *Headers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Headers.Merge(m, src)
}
func (m *Headers) XXX_Size() int {
	return xxx_messageInfo_Headers.Size(m)
}
func (m *Headers) XXX_DiscardUnknown() {
	xxx_messageInfo_Headers.DiscardUnknown(m)
}

var xxx_messageInfo_Headers proto.InternalMessageInfo

func (m *Headers) GetMessageId() uint32 {
	if m != nil {
		return m.MessageId
	}
	return 0
}

func (m *Headers) GetParentMessageId() uint32 {
	if m != nil {
		return m.ParentMessageId
	}
	return 0
}

func (m *Headers) GetEpisodeId() uint32 {
	if m != nil {
		return m.EpisodeId
	}
	return 0
}

type Body struct {
	EnvId                string   `protobuf:"bytes,1,opt,name=EnvId,json=envId,proto3" json:"EnvId,omitempty"`
	EnvStatus            string   `protobuf:"bytes,2,opt,name=EnvStatus,json=envStatus,proto3" json:"EnvStatus,omitempty"`
	Fps                  float32  `protobuf:"fixed32,3,opt,name=Fps,json=fps,proto3" json:"Fps,omitempty"`
	Reward               float32  `protobuf:"fixed32,4,opt,name=Reward,json=reward,proto3" json:"Reward,omitempty"`
	Done                 bool     `protobuf:"varint,5,opt,name=Done,json=done,proto3" json:"Done,omitempty"`
	Record               bool     `protobuf:"varint,6,opt,name=Record,json=record,proto3" json:"Record,omitempty"`
	Obs                  string   `protobuf:"bytes,7,opt,name=Obs,json=obs,proto3" json:"Obs,omitempty"`
	ObsType              string   `protobuf:"bytes,8,opt,name=ObsType,json=obsType,proto3" json:"ObsType,omitempty"`
	Info                 string   `protobuf:"bytes,9,opt,name=Info,json=info,proto3" json:"Info,omitempty"`
	InfoType             string   `protobuf:"bytes,10,opt,name=InfoType,json=infoType,proto3" json:"InfoType,omitempty"`
	Message              string   `protobuf:"bytes,11,opt,name=Message,json=message,proto3" json:"Message,omitempty"`
	Seed                 uint32   `protobuf:"varint,12,opt,name=Seed,json=seed,proto3" json:"Seed,omitempty"`
	Action               []byte   `protobuf:"bytes,13,opt,name=Action,json=action,proto3" json:"Action,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Body) Reset()         { *m = Body{} }
func (m *Body) String() string { return proto.CompactTextString(m) }
func (*Body) ProtoMessage()    {}
func (*Body) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a4e87e678c5ced, []int{1}
}

func (m *Body) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Body.Unmarshal(m, b)
}
func (m *Body) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Body.Marshal(b, m, deterministic)
}
func (m *Body) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Body.Merge(m, src)
}
func (m *Body) XXX_Size() int {
	return xxx_messageInfo_Body.Size(m)
}
func (m *Body) XXX_DiscardUnknown() {
	xxx_messageInfo_Body.DiscardUnknown(m)
}

var xxx_messageInfo_Body proto.InternalMessageInfo

func (m *Body) GetEnvId() string {
	if m != nil {
		return m.EnvId
	}
	return ""
}

func (m *Body) GetEnvStatus() string {
	if m != nil {
		return m.EnvStatus
	}
	return ""
}

func (m *Body) GetFps() float32 {
	if m != nil {
		return m.Fps
	}
	return 0
}

func (m *Body) GetReward() float32 {
	if m != nil {
		return m.Reward
	}
	return 0
}

func (m *Body) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

func (m *Body) GetRecord() bool {
	if m != nil {
		return m.Record
	}
	return false
}

func (m *Body) GetObs() string {
	if m != nil {
		return m.Obs
	}
	return ""
}

func (m *Body) GetObsType() string {
	if m != nil {
		return m.ObsType
	}
	return ""
}

func (m *Body) GetInfo() string {
	if m != nil {
		return m.Info
	}
	return ""
}

func (m *Body) GetInfoType() string {
	if m != nil {
		return m.InfoType
	}
	return ""
}

func (m *Body) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Body) GetSeed() uint32 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *Body) GetAction() []byte {
	if m != nil {
		return m.Action
	}
	return nil
}

type Message struct {
	Method               string   `protobuf:"bytes,1,opt,name=Method,json=method,proto3" json:"Method,omitempty"`
	Headers              *Headers `protobuf:"bytes,2,opt,name=Headers,json=headers,proto3" json:"Headers,omitempty"`
	Body                 *Body    `protobuf:"bytes,3,opt,name=Body,json=body,proto3" json:"Body,omitempty"`
	Timestamp            uint32   `protobuf:"varint,4,opt,name=Timestamp,json=timestamp,proto3" json:"Timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_d8a4e87e678c5ced, []int{2}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func (m *Message) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *Message) GetHeaders() *Headers {
	if m != nil {
		return m.Headers
	}
	return nil
}

func (m *Message) GetBody() *Body {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *Message) GetTimestamp() uint32 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func init() {
	proto.RegisterType((*Headers)(nil), "proto.Headers")
	proto.RegisterType((*Body)(nil), "proto.Body")
	proto.RegisterType((*Message)(nil), "proto.Message")
}

func init() { proto.RegisterFile("shared.proto", fileDescriptor_d8a4e87e678c5ced) }

var fileDescriptor_d8a4e87e678c5ced = []byte{
	// 367 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x91, 0x4f, 0x8a, 0xdb, 0x30,
	0x18, 0xc5, 0xf1, 0x7f, 0x5b, 0x4e, 0x9a, 0x22, 0x4a, 0x11, 0x25, 0x50, 0x93, 0x95, 0x57, 0x59,
	0xa4, 0x27, 0x68, 0x69, 0x4a, 0xb3, 0x08, 0x29, 0x4a, 0x2e, 0x20, 0x47, 0x5f, 0x1a, 0x2f, 0x2c,
	0x19, 0x49, 0x93, 0x21, 0x57, 0x98, 0xe3, 0xcc, 0x09, 0x07, 0x7d, 0xb6, 0x33, 0xcc, 0xca, 0xbc,
	0x1f, 0xcf, 0xef, 0x13, 0xef, 0x91, 0x99, 0xbd, 0x0a, 0x03, 0x72, 0xdd, 0x1b, 0xed, 0x34, 0x4d,
	0xf0, 0xb3, 0xd2, 0x24, 0xfb, 0x0b, 0x42, 0x82, 0xb1, 0x74, 0x49, 0x8a, 0x3d, 0x58, 0x2b, 0xfe,
	0xc3, 0x4e, 0xb2, 0xb0, 0x0a, 0xea, 0x39, 0x2f, 0xba, 0x09, 0xd0, 0x9a, 0x2c, 0xfe, 0x09, 0x03,
	0xca, 0xbd, 0x7b, 0x22, 0xf4, 0x2c, 0xfa, 0x8f, 0xd8, 0xe7, 0x6c, 0xfb, 0xd6, 0x6a, 0xe9, 0x3d,
	0xf1, 0x90, 0x03, 0x13, 0x58, 0xbd, 0x86, 0x24, 0xfe, 0xa5, 0xe5, 0x9d, 0x7e, 0x21, 0xc9, 0x56,
	0xdd, 0x76, 0x92, 0x05, 0x55, 0x50, 0x17, 0x3c, 0x01, 0x2f, 0xf0, 0x67, 0x75, 0x3b, 0x3a, 0xe1,
	0x9e, 0x2c, 0x3e, 0xa2, 0xe0, 0x05, 0x4c, 0x80, 0x7e, 0x26, 0xd1, 0x9f, 0xde, 0xe2, 0xe1, 0x90,
	0x47, 0x97, 0xde, 0xd2, 0xaf, 0x24, 0xe5, 0xf0, 0x2c, 0xcc, 0x70, 0x29, 0xe4, 0xa9, 0x41, 0x45,
	0x29, 0x89, 0x7f, 0x6b, 0x05, 0x2c, 0xa9, 0x82, 0x3a, 0xe7, 0xb1, 0xd4, 0x0a, 0x06, 0xef, 0x59,
	0x1b, 0xc9, 0x52, 0xa4, 0xa9, 0x41, 0xe5, 0x53, 0x0f, 0x8d, 0x65, 0x19, 0x5e, 0x8b, 0x74, 0x63,
	0x29, 0x23, 0xd9, 0xa1, 0xb1, 0xa7, 0x7b, 0x0f, 0x2c, 0x47, 0x9a, 0xe9, 0x41, 0xfa, 0xdc, 0x9d,
	0xba, 0x68, 0x56, 0x20, 0x8e, 0x5b, 0x75, 0xd1, 0xf4, 0x1b, 0xc9, 0x3d, 0x43, 0x3b, 0x41, 0x9e,
	0xb7, 0xa3, 0xf6, 0x49, 0x63, 0x33, 0xac, 0x1c, 0x92, 0xc6, 0x4a, 0x7d, 0xd2, 0x11, 0x40, 0xb2,
	0x19, 0x36, 0x14, 0x5b, 0x00, 0xe9, 0x5f, 0xf8, 0xf3, 0xec, 0x5a, 0xad, 0xd8, 0xbc, 0x0a, 0xea,
	0x19, 0x4f, 0x05, 0xaa, 0xd5, 0x4b, 0xf0, 0x88, 0xf1, 0x9e, 0x3d, 0xb8, 0xab, 0x9e, 0x8a, 0x4b,
	0x3b, 0x54, 0xb4, 0x7e, 0x2c, 0x89, 0xbd, 0x95, 0x9b, 0x4f, 0xc3, 0xd2, 0xeb, 0x91, 0xf2, 0xec,
	0x3a, 0x0e, 0xfd, 0x7d, 0x58, 0x00, 0x6b, 0x2c, 0x37, 0xe5, 0x68, 0xf3, 0x88, 0xc7, 0x8d, 0x9f,
	0x66, 0x49, 0x8a, 0x53, 0xdb, 0x81, 0x75, 0xa2, 0xeb, 0xa7, 0x05, 0xdd, 0x04, 0x9a, 0x14, 0xfd,
	0x3f, 0xde, 0x02, 0x00, 0x00, 0xff, 0xff, 0x41, 0x36, 0xd0, 0x5f, 0x50, 0x02, 0x00, 0x00,
}
